services:
  - type: web
    name: time-ai-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://samay-sahayak.vercel.app
      - key: GEMINI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false 